---
- name: Nodejs service deployment
  hosts: all
  remote_user: ubuntu
  become: true
  become_user: root
  gather_facts: false
  vars_files:
    - vault/secrets.yml
  roles:
    - role: server
      tags: server
    - role: app
      tags: app
