# SPDX-License-Identifier: MIT-0
---
# tasks file for docker
- name: Yum update
  ansible.builtin.dnf:
    update_cache: true

- name: Install docker
  ansible.builtin.dnf:
    name: docker
    state: present
  notify: Restart docker

- name: Ensure CLI plugin directory exists
  ansible.builtin.file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory
    mode: "755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true

- name: Download Docker Compose v2 binary
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.36.2/docker-compose-linux-x86_64
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    mode: "755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Add user to docker group
  ansible.builtin.user:
    name: ec2-user
    group: docker
