# SPDX-License-Identifier: MIT-0
---
# tasks file for app

# clone repo
- name: Get file metadata from GitHub API
  ansible.builtin.uri:
    url: https://api.github.com/repos/pedralmeida22/roadmap_devops/contents/nodejs-service-deployment/app
    headers:
      Authorization: "Bearer {{ app_gh_token }}"
  register: file_metadata

- name: Download the file from the actual download URL
  ansible.builtin.get_url:
    url: "{{ file_metadata.json.download_url }}"
    dest: /home/ubuntu/
    mode: "664"

# install dependencies

# build, run and start app
