# SPDX-License-Identifier: MIT-0
---
# tasks file for app

- name: Create app directory
  ansible.builtin.file:
    path: /home/ubuntu/app/
    state: directory
    mode: "775"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Get file metadata from GitHub API
  ansible.builtin.uri:
    url: https://api.github.com/repos/pedralmeida22/roadmap_devops/contents/nodejs-service-deployment/app
    headers:
      Authorization: "Bearer {{ app_gh_token }}"
  register: file_metadata

- name: Download the each file from the app directory
  ansible.builtin.get_url:
    url: "{{ loop_item.download_url }}"
    dest: /home/ubuntu/app/
    mode: "664"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop: "{{ file_metadata.json }}"
  loop_control:
    loop_var: loop_item

# install dependencies
- name: Install dependencies
  community.general.npm:
    path: /home/ubuntu/app

- name: Add systemd service file
  ansible.builtin.copy:
    src: node_systemd.service
    dest: /etc/systemd/system/
    mode: "664"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Enable and start systemd service
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    enabled: true
    name: node_systemd
