# SPDX-License-Identifier: MIT-0
---
# tasks file for app
- name: Create /var/www/html directory
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    mode: "775"

- name: Upload website tarball
  ansible.builtin.copy:
    src: /Users/almeida-mba/Documents/roadmap/roadmap_devops/configuration-management/website.zip
    dest: /tmp/website.zip
    mode: "664"
  tags: v1

- name: Get file metadata from GitHub API
  ansible.builtin.uri:
    url: https://api.github.com/repos/pedralmeida22/roadmap_devops/contents/configuration-management/website.zip
    headers:
      Authorization: "Bearer {{ app_gh_token }}"
  register: file_metadata

- name: Download the file from the actual download URL
  ansible.builtin.get_url:
    url: "{{ file_metadata.json.download_url }}"
    dest: /tmp/website.zip
    mode: "664"

- name: Unarchive website tarball
  ansible.builtin.unarchive:
    src: /tmp/website.zip
    dest: /var/www/html
    remote_src: true
