# SPDX-License-Identifier: MIT-0
---
# tasks file for base
- name: Apt update
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install packages
  ansible.builtin.apt:
    state: present
    name:
      - git
      - nano
      - unzip

- name: Start and enable firewall (ufw)
  ansible.builtin.systemd_service:
    name: ufw
    enabled: true
    state: started
