---
- name: Configure server
  hosts: all
  remote_user: ec2-user
  become: true
  become_user: root
  gather_facts: false
  vars_files:
    - secrets.yml
  roles:
    - role: docker
      tags: docker
  tasks:
    - name: Create app directory
      ansible.builtin.file:
        path: /home/ec2-user/app
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "775"

    - name: Get file metadata from GitHub API
      ansible.builtin.uri:
        url: https://api.github.com/repos/pedralmeida22/roadmap_devops/contents/multi-container-app/docker-compose.yml
        headers:
          Authorization: "Bearer {{ gh_token }}"
      register: file_metadata

    - name: Download docker compose file download URL
      ansible.builtin.get_url:
        url: "{{ file_metadata.json.download_url }}"
        dest: /home/ec2-user/app
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "664"

    - name: Log into the private registry
      community.docker.docker_login:
        username: "{{ dh_username }}"
        password: "{{ dh_token }}"

    - name: Pull todos_api docker image from registry
      community.docker.docker_image:
        source: pull
        name: pedralmeida/todos_api:latest

    - name: Pull mongo docker image from registry
      community.docker.docker_image:
        source: pull
        name: mongo:latest

    - name: Stop old containers
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user/app/
        state: absent

    - name: Start new containers
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user/app/
        state: present
