name: Deploy nodejs application
run-name: ${{ github.actor }} deploying app...

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths:
      - "nodejs-service-deployment/app/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Install python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo -e "Host *\n  StrictHostKeyChecking=no\n  UserKnownHostsFile=/dev/null" > ~/.ssh/config
          chmod 600 ~/.ssh/id_rsa

      - name: Run playbook
        working-directory: ./nodejs-service-deployment/ansible
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASSWORD }}
        run: |
          echo "$VAULT_PASS" > ./nodejs-service-deployment/ansible/vault_pass.txt
          ansible-playbook playbook.yml -i inventory/inventory.yml --tags "app" --vault-password-file vaul_pass.txt
